FrontEnd/WebUI/Areas/Admin/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Core.Filters;
using Core.Models;
using Core.Views;
using Telerik.Web.Mvc;

namespace WebUI.Areas.Admin.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class PictureController : Controller
    {
        private readonly IBaseRepository<Picture> _rPicture;

        public PictureController(IBaseRepository<Picture> rPicture)
        {
            _rPicture = rPicture;
        }
        public ActionResult Index()
        {
            return View();
        }

        [GridAction]
        public ActionResult _Index()
        {
            var pictures = (from p in _rPicture.GetAll().ToList()
                             select new PictureView
                             {
                                 PictureId = p.PictureId,
                                 MakeDate = p.MakeDate,
                                 FileName = p.FileName,
                                 FileType = p.FileType
                             });

            return View(new GridModel(pictures.ToList()));
        }

        public void _Upload(HttpPostedFileBase attachments = null)
        {
            if (attachments != null)
            {
                var picture = new Picture();

                var br = new BinaryReader(attachments.InputStream);
                picture.MakeDate = DateTime.Now;
                picture.FileContent = br.ReadBytes(attachments.ContentLength);
                picture.FileName = Path.GetFileName(attachments.FileName);
                picture.FileType = attachments.ContentType;
                _rPicture.Create(picture);                
            }  
        }

        [OutputCache(Duration = 600, Location = OutputCacheLocation.Server, VaryByParam = "pictureId")]
        public FileContentResult GetImage(int pictureId)
        {
            Picture photo = _rPicture.Get(p => p.PictureId == pictureId);
            return File(photo.FileContent, photo.FileType);
        }

        [GridAction]
        public ActionResult _Delete(int id)
        {
            var picture = _rPicture.Get(p => p.PictureId == id);
            _rPicture.Delete(picture);

            var pictures = (from p in _rPicture.GetAll().ToList()
                            select new PictureView
                            {
                                PictureId = p.PictureId,
                                MakeDate = p.MakeDate,
                                FileName = p.FileName,
                                FileType = p.FileType
                            });

            return View(new GridModel(pictures.ToList()));
        }

    }
}

FrontEnd/WebUI/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Filters;

namespace WebUI.Areas.Customer.Controllers
{
    [CustomAuthorize(Roles = "Admin, Customer")]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

FrontEnd/WebUI/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "IT Management";
}
@section Meta {
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
}

<div style="height: 375px;">
    @Html.Action("SlideShow", "Picture", new { area = "Customer" })
</div>

<div style="height: 5px; border: 1px solid #c3c3c3; background-color: #e8e8e8; margin-top: 10px;">
    &nbsp
</div>

<table style="width: 100%">
    <tr>
        <td style="width: 50%; padding: 0px 0px; vertical-align: top;">
            <div class="page-title">
                <h2> События на портале </h2>
            </div>
            <div>
                @Html.Action("_Index", "LogAppEvent", new { area = "Customer" })
            </div>
        </td>
        <td style="width: 50%; padding: 0px 0px; vertical-align: top;">
            <div class="page-title">
                <h2> Работа на портале (справка) </h2>
            </div>
            <div>
                @Html.Action("_Index", "HelpArticle", new { area = "Customer" })                
            </div>
        </td>
    </tr>
</table>

@section Scripts{
    <script src="@Url.Content("~/Scripts/SlideShow.js")" type="text/javascript"></script>
}