FrontEnd/WebUI/Controllers/InformationController.cs
using Core.Filters;
using Core.Providers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Others;

namespace WebUI.Controllers
{    
    [CustomAuthorize(Roles = "Admin, Customer")]
    public class InformationController : Controller
    {
        private readonly ActiveDirectoryProvider _rActiveDirectoryProvide;
        private readonly ICalendarLogic _lCalendar;

        public InformationController(ActiveDirectoryProvider rActiveDirectoryProvide, ICalendarLogic lCalendar)
        {
            _lCalendar = lCalendar;
            _rActiveDirectoryProvide = rActiveDirectoryProvide;
        }

        public ContentResult DisplayName()
        {
            var displayName = _rActiveDirectoryProvide.GetUserDisplayName(User.Identity.Name);
            return Content(displayName, "text/html");
        }

        public ContentResult CalculusPeriod()
        {
            var codeMonth = Convert.ToInt32(Session["CurrentCodeMonth"]);
            var currentDate = _lCalendar.GetDateByCodeMonth(codeMonth);

            return Content("Учетный период: " + currentDate.ToString("MMMM") +
                " '" + currentDate.ToString("yy"), "text/html");
        }
    }
}

FrontEnd/WebUI/Controllers/RawEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Models;
using Core.Views;
using Telerik.Web.Mvc;
using Business.ServerSide;
using Core.Filters;

namespace WebUI.Controllers
{
    [CustomAuthorize(Roles = "Admin, Customer")]
    public class RawEmployeeController : Controller
    {
        private readonly IBaseRepository<RawEmployee> _rRawEmployee;
        private readonly IBaseRepository<Employee> _rEmployee;
        private readonly IBaseRepository<CostCenter> _rCostCenter;
        private readonly IBaseRepository<Position> _rPosition;
        private readonly IBaseRepository<Company> _rCompany;
        private readonly IBaseRepository<Department> _rDepartment;
        private readonly IImportDataServer _sImportDataServer;

        public RawEmployeeController(IBaseRepository<RawEmployee> rRawEmployee,
            IBaseRepository<Employee> rEmployee, IBaseRepository<CostCenter> rCostCenter,
            IBaseRepository<Position> rPosition, IBaseRepository<Company> rCompany, 
            IBaseRepository<Department> rDepartment, IImportDataServer sImportDataServer)
        {
            _rRawEmployee = rRawEmployee;
            _rEmployee = rEmployee;
            _rCostCenter = rCostCenter;
            _rPosition = rPosition;
            _rCompany = rCompany;
            _rDepartment = rDepartment;
            _sImportDataServer = sImportDataServer;
        }

        public ActionResult Index(string layout)
        {
            var costCenters = (from p in _rCostCenter.GetAll().ToList()
                               select new CostCenterShortView
                               {
                                   CostCenterId = p.CostCenterId,                                   
                                   Name = p.Code + (p.Code != null && p.Name != null ? " - " : "") + p.Name
                               });
            var departments = (from p in _rDepartment.GetAll().ToList()
                               select new DepartmentShortView
                               {
                                   DepartmentId = p.DepartmentId,
                                   Name = p.Code + (p.Code != null && p.Name != null ? " - " : "") + p.Name
                               });

            ViewBag.Employees = new SelectList(_rEmployee.GetAll(), "EmployeeId", "Fullname");
            ViewBag.CostCenters = new SelectList(costCenters, "CostCenterId", "Name");
            ViewBag.Positions = new SelectList(_rPosition.GetAll(), "PositionId", "Name");
            ViewBag.Companies = new SelectList(_rCompany.GetAll(), "CompanyId", "Name");
            ViewBag.Departments = new SelectList(departments, "DepartmentId", "Name");

            if (layout == "Admin")
            {
                return View("Index", "~/Areas/Admin/Views/Shared/_Layout.cshtml");
            }
            else
            {
                return View("Index", "~/Areas/Customer/Views/Shared/_Layout.cshtml");
            }
        }

        #region CRUD

        [GridAction]
        public ActionResult _Index()
        {
            var rawEmployees = (from p in _rRawEmployee.GetAll().ToList()
                                select new RawEmployeeView { 
                                   RawEmployeeId = p.RawEmployeeId,                                   
                                   RawAuthid = p.RawAuthid,
                                   CompanyId = (p.Company != null ? p.Company.Name : ""),
                                   RawCostCenter = p.RawCostCenter,
                                   CostCenterId = (p.CostCenter != null ? 
                                        (p.CostCenter.Code + (p.CostCenter.Code != null && p.CostCenter.Name != null ? " - " : "") + p.CostCenter.Name) : ""),                                        
                                   RawDepartmentCode = p.RawDepartmentCode,
                                   RawDepartmentCodes = p.RawDepartmentCodes,
                                   RawDepartmentNames = p.RawDepartmentNames,
                                   DepartmentId = (p.Department != null ?
                                        (p.Department.Code + (p.Department.Code != null && p.Department.Name != null ? " - " : "") + p.Department.Name) : "" ),
                                   RawDischargeDate = p.RawDischargeDate,
                                   RawEMail = p.RawEMail,
                                   RawFirstname = p.RawFirstname,
                                   RawMiddlename = p.RawMiddlename,
                                   RawFullname = (p.RawSurname != null ? p.RawSurname + " " : "") +
                                        (p.RawFirstname != null ? p.RawFirstname + " " : "") + (p.RawMiddlename != null ? p.RawMiddlename : ""),
                                   EmployeeId = (p.Employee != null ? p.Employee.Fullname : ""),
                                   RawPosition = p.RawPosition,
                                   PositionId = (p.Position != null ? p.Position.Name : ""),
                                   RawSurname = p.RawSurname                                   
                               });
            return View(new GridModel(rawEmployees));
        }

        [GridAction]
        public ActionResult _CreateUpdate(RawEmployee rawEmployee)
        {
            if (rawEmployee.RawEmployeeId.Equals(0))
            {
                _rRawEmployee.Create(rawEmployee);
            }
            else
            {
                _rRawEmployee.Update(rawEmployee);
            }

            rawEmployee.CostCenter = _rCostCenter.Get(p => p.CostCenterId == rawEmployee.CostCenterId);
            rawEmployee.Employee = _rEmployee.Get(p => p.EmployeeId == rawEmployee.EmployeeId);
            rawEmployee.Position = _rPosition.Get(p => p.PositionId == rawEmployee.PositionId);
            rawEmployee.Company = _rCompany.Get(p => p.CompanyId == rawEmployee.CompanyId);

            var rawEmployees = (from p in _rRawEmployee.GetAll().ToList()
                                select new RawEmployeeView
                                {
                                    RawEmployeeId = p.RawEmployeeId,
                                    RawAuthid = p.RawAuthid,
                                    CompanyId = (p.Company != null ? p.Company.Name : ""),
                                    RawCostCenter = p.RawCostCenter,
                                    CostCenterId = (p.CostCenter != null ?
                                        (p.CostCenter.Code + (p.CostCenter.Code != null && p.CostCenter.Name != null ? " - " : "") + p.CostCenter.Name) : ""),
                                    RawDepartmentCode = p.RawDepartmentCode,
                                    RawDepartmentCodes = p.RawDepartmentCodes,
                                    RawDepartmentNames = p.RawDepartmentNames,
                                    DepartmentId = (p.Department != null ?
                                        (p.Department.Code + (p.Department.Code != null && p.Department.Name != null ? " - " : "") + p.Department.Name) : ""),
                                    RawDischargeDate = p.RawDischargeDate,
                                    RawEMail = p.RawEMail,
                                    RawFirstname = p.RawFirstname,
                                    RawMiddlename = p.RawMiddlename,
                                    RawFullname = (p.RawSurname != null ? p.RawSurname + " " : "") +
                                         (p.RawFirstname != null ? p.RawFirstname + " " : "") + (p.RawMiddlename != null ? p.RawMiddlename : ""),
                                    EmployeeId = (p.Employee != null ? p.Employee.Fullname : ""),
                                    RawPosition = p.RawPosition,
                                    PositionId = (p.Position != null ? p.Position.Name : ""),
                                    RawSurname = p.RawSurname
                                });
            return View(new GridModel(rawEmployees));
        }

        [GridAction]
        public ActionResult _Delete(int id)
        {
            var rawEmployee = _rRawEmployee.Get(p => p.RawEmployeeId == id);
            _rRawEmployee.Delete(rawEmployee);

            var rawEmployees = (from p in _rRawEmployee.GetAll().ToList()
                                select new RawEmployeeView
                                {
                                    RawEmployeeId = p.RawEmployeeId,
                                    RawAuthid = p.RawAuthid,
                                    CompanyId = (p.Company != null ? p.Company.Name : ""),
                                    RawCostCenter = p.RawCostCenter,
                                    CostCenterId = (p.CostCenter != null ?
                                        (p.CostCenter.Code + (p.CostCenter.Code != null && p.CostCenter.Name != null ? " - " : "") + p.CostCenter.Name) : ""),
                                    RawDepartmentCode = p.RawDepartmentCode,
                                    RawDepartmentCodes = p.RawDepartmentCodes,
                                    RawDepartmentNames = p.RawDepartmentNames,
                                    DepartmentId = (p.Department != null ?
                                        (p.Department.Code + (p.Department.Code != null && p.Department.Name != null ? " - " : "") + p.Department.Name) : ""),
                                    RawDischargeDate = p.RawDischargeDate,
                                    RawEMail = p.RawEMail,
                                    RawFirstname = p.RawFirstname,
                                    RawMiddlename = p.RawMiddlename,
                                    RawFullname = (p.RawSurname != null ? p.RawSurname + " " : "") +
                                         (p.RawFirstname != null ? p.RawFirstname + " " : "") + (p.RawMiddlename != null ? p.RawMiddlename : ""),

FrontEnd/WebUI/Controllers/RawSystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.ServerSide;
using Core.Filters;
using Core.Models;
using Core.Views;
using Telerik.Web.Mvc;

namespace WebUI.Controllers
{
    [CustomAuthorize(Roles = "Admin, Customer")]
    public class RawSystemController : Controller
    {
        private readonly IBaseRepository<RawSystem> _rRawSystem;
        private readonly IBaseRepository<Employee> _rEmployee;
        private readonly IBaseRepository<Company> _rCompany;
        private readonly IImportDataServer _sImportData;

        public RawSystemController(IBaseRepository<RawSystem> rRawSystem,
            IBaseRepository<Employee> rEmployee, IBaseRepository<Company> rCompany,
            IImportDataServer sImportData)
        {
            _rRawSystem = rRawSystem;
            _rEmployee = rEmployee;
            _rCompany = rCompany;
            _sImportData = sImportData;
        }

        public ActionResult Index(string layout)
        {
            var isDisplayActiveOnly = Convert.ToBoolean(Session["IsDisplayActiveOnly"]);
            ViewBag.Employees = new SelectList(_rEmployee.GetList(p => (isDisplayActiveOnly ? p.IsActive == true : true)) , "EmployeeId", "Fullname");
            ViewBag.Companies = new SelectList(_rCompany.GetAll(), "CompanyId", "Name");

            if (layout == "Admin")
            {
                return View("Index", "~/Areas/Admin/Views/Shared/_Layout.cshtml");
            }
            else
            {
                return View("Index", "~/Areas/Customer/Views/Shared/_Layout.cshtml");
            }    
        }

        #region CRUD

        [GridAction]
        public ActionResult _Index()
        {
            var rawSystems = (from p in _rRawSystem.GetAll().ToList()
                              select new RawSystemView
                              {
                                  AgentTime = p.AgentTime,
                                  CompanyId = (p.Company != null ? p.Company.Name : ""),
                                  EmployeeId = (p.Employee != null ? p.Employee.Fullname : ""),
                                  Netbios_Name0 = p.Netbios_Name0,
                                  Operating_System_Name_and0 = p.Operating_System_Name_and0,
                                  RawSystemId = p.RawSystemId,
                                  ResourceId = p.ResourceId,
                                  User_Domain0 = p.User_Domain0,
                                  User_Name0 = p.User_Name0
                              });

            return View(new GridModel(rawSystems));
        }

        [GridAction]
        public ActionResult _CreateUpdate(RawSystem rawSystem)
        {
            if (ModelState.IsValid)
            {
                if (rawSystem.RawSystemId.Equals(0))
                {
                    _rRawSystem.Create(rawSystem);
                }
                else
                {
                    _rRawSystem.Update(rawSystem);
                }
                rawSystem.Company = _rCompany.Get(p => p.CompanyId == rawSystem.CompanyId);
                rawSystem.Employee = _rEmployee.Get(p => p.EmployeeId == rawSystem.EmployeeId);
            }

            var rawSystems = (from p in _rRawSystem.GetAll().ToList()
                              select new RawSystemView
                              {
                                  AgentTime = p.AgentTime,
                                  CompanyId = (p.Company != null ? p.Company.Name : ""),
                                  EmployeeId = (p.Employee != null ? p.Employee.Fullname : ""),
                                  Netbios_Name0 = p.Netbios_Name0,
                                  Operating_System_Name_and0 = p.Operating_System_Name_and0,
                                  RawSystemId = p.RawSystemId,
                                  ResourceId = p.ResourceId,
                                  User_Domain0 = p.User_Domain0,
                                  User_Name0 = p.User_Name0
                              });

            return View(new GridModel(rawSystems));
        }

        [GridAction]
        public ActionResult _Delete(int id)
        {
            var rawSystem = _rRawSystem.Get(p => p.RawSystemId == id);
            _rRawSystem.Delete(rawSystem);

            var rawSystems = (from p in _rRawSystem.GetAll().ToList()
                              select new RawSystemView
                              {
                                  AgentTime = p.AgentTime,
                                  CompanyId = (p.Company != null ? p.Company.Name : ""),
                                  EmployeeId = (p.Employee != null ? p.Employee.Fullname : ""),
                                  Netbios_Name0 = p.Netbios_Name0,
                                  Operating_System_Name_and0 = p.Operating_System_Name_and0,
                                  RawSystemId = p.RawSystemId,
                                  ResourceId = p.ResourceId,
                                  User_Domain0 = p.User_Domain0,
                                  User_Name0 = p.User_Name0
                              });

            return View(new GridModel(rawSystems));
        }

        #endregion

        #region Import

        [HttpPost]
        public ContentResult _Import()
        {
            return Content(_sImportData.ImportSystem());
        }

        [HttpPost]
        public ContentResult _Parse()
        {
            return Content(_sImportData.ParseSystem());
        }

        [HttpPost]
        public ContentResult _Load()
        {
            return Content(_sImportData.LoadSystem());
        }

        #endregion

    }
}

FrontEnd/WebUI/Areas/Customer/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Meta { @RenderSection("Meta", required: false) }

@section Header {
    <div class="float-left">
        <div class="header-content">
          @*  <img src="~/Images/Logos/OrengurgneftLarge.png" />*@
        </div>
        <div class="header-content">
            <h1>Учет лицензий и ИТ Услуг</h1>
        </div>        
    </div>
    <div class="float-right" style="text-align: center; padding: 10px;">      
        <div style="line-height:16px; font-size:16px; margin: 5px; color: #2a326b">
            @Html.Action("CalculusPeriod", "Information", new { area = ""})        
        </div>
        <div style="line-height:16px; margin: 5px; color: #2a326b">
            @*@Html.Action("DisplayName", "Information", new { area = "" })*@
            @Html.ActionLink("Профиль: " + Html.Action("DisplayName", "Information", new { area = "" }).ToString(),
                "Edit", "EmployeeProfile")
        </div>        
    </div>
    @*<div class="clear-float" />  *@
    <div class="clear-float"></div>
}

@section Menu {
    <ul class="main-menu">
        <li> @Html.ActionLink("НА ГЛАВНУЮ", "Index", "Home", new { area = "Customer" }, null) </li>
        <li> <a> УЧЕТ УСЛУГ </a> 
            <ul>
                <li> @Html.ActionLink("Ввод данных", "IndexHierarchy", "MaintenanceOrder", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Журнал услуг", "IndexTable", "MaintenanceOrder", new { area = "Customer" }, null) </li>   
                <li> @Html.ActionLink("Тарифы", "Index", "Tariff", new { area = "Customer" }, null)</li>
                <li> @Html.ActionLink("Услуги компании", "Index", "CompanyMaintenance", new { area = "Customer" }, null) </li>
                @*<li> @Html.ActionLink("Правила заполнения", "Index", "Tariff", new { area = "Customer" }, null) </li>*@
                <li> @Html.ActionLink("ИТ услуги", "Index", "Maintenance", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Сервисные линии", "Index", "ServiceLine", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Компоненты услуги", "Index", "Component", new { area = "Customer" }, null) </li>
            </ul>
        </li>
        <li> <a> УЧЕТ ЛИЦЕНЗИЙ </a> 
            <ul>
                <li> @Html.ActionLink("Ввод данных", "Index", "License", new { area = "Customer" }, null) </li>  
                <li> @Html.ActionLink("Подготовка данных", "Index", "ContractorSoftware", new { area = "Customer" }, null) </li>
                @*<li> @Html.ActionLink("Список ПО по пользов-ям", "Index", "InstalledSoftware", new { area = "Customer" }, null) </li>*@
                @*<li> @Html.ActionLink("Привязка лицензий", "Index", "ContractorSoftwareLicense", new { area = "Customer" }, null) </li>                 *@                          
                <li> @Html.ActionLink("Программное обеспечение", "Index", "Software", new { area = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Модули ПО", "Index", "SoftwareModule", new { area = "Customer" }, null) </li> 
                <li> @Html.ActionLink("Типы ПО", "Index", "SoftwareType", new { area = "Customer" }, null) </li>                
            </ul>
        </li>
        <li> <a> СПРАВОЧНИКИ </a>
            <ul>                            
                <li> @Html.ActionLink("Сотрудники", "Index", "Employee", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("МВЗ", "Index", "CostCenter", new { area = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Подразделения", "IndexHierarchy", "Department", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Контрагенты", "Index", "Contractor", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Должности", "Index", "Position", new { area = "Customer" }, null) </li>
            </ul>
        </li>
        <li> <a> ОТЧЕТЫ </a> 
            <ul>
                <li> @Html.ActionLink("Отчет по лицензиям", "UsedLicense", "Report", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Список ПО по пользов-ям", "InstalledSoftware", "Report", new { area = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Шахматка по услугам", "MaintenanceCross", "Report", new { area = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Шахматка v2","Chess", "Report", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Круглосуточные услуги", "R24HoursMaintenance", "Report", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Акт выполненных работ","Invoice", "Report", new { area = "Customer" }, null) </li>                
                @*<li> <a> Отчет по лицензиям </a> </li>*@
            </ul>
        </li>
        <li> <a> ОБМЕН ДАННЫМИ </a> 
            <ul>
                <li> @Html.ActionLink("МВЗ из Excel", "Index", "RawCostCenter", new { area = "Customer" }, null) </li> 
                <li> @Html.ActionLink("Услуги SAP из Excel", "Index", "RawSAPMaintenance", new { area = "", layout = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Услуги из Excel", "Index", "RawMaintenanceByUser", new { area = "", layout = "Customer" }, null) </li>                                                       
                <li> @Html.ActionLink("Услуги из AD", "Index", "RawADMaintenance", new { area = "", layout = "Customer" }, null) </li>        
                <li> @Html.ActionLink("Сотрудники из ЕКС", "Index", "RawEmployee", new { area = "", layout = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Компьютеры из MS SMS", "Index", "RawSystem", new { area = "", layout = "Customer" }, null) </li>  
                <li> @Html.ActionLink("Установл. ПО из MS SMS", "Index", "RawInstalledSoftware", new { area = "", layout = "Customer" }, null) </li>  
            </ul>
        </li>       
    </ul>
}

@RenderBody() 

@section Footer {
    <div class="footer-title"> БЫСТРЫЕ ССЫЛКИ </div>
                
    <ul class="links">
        <li>
            <div class="sub-title"> УСЛУГИ </div>
            <ul class="items">
                <li> @Html.ActionLink("Ввод данных по услугам", "IndexHierarchy", "MaintenanceOrder", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("Журнал услуг", "IndexTable", "MaintenanceOrder", new { area = "Customer" }, null) </li>      
                <li> @Html.ActionLink("Услуги компании", "Index", "CompanyMaintenance", new { area = "Customer" }, null) </li>                
            </ul>
        </li>
        <li>
            <div class="sub-title"> ЛИЦЕНЗИИ </div>
            <ul class="items">                
                <li> @Html.ActionLink("Ввод данных по лицензиям", "Index", "License", new { area = "Customer" }, null) </li>   
                <li> @Html.ActionLink("Подготовка данных", "Index", "ContractorSoftware", new { area = "Customer" }, null) </li>                
                <li> <a> &nbsp; </a> </li>   
            </ul>
        </li>
        <li>
            <div class="sub-title"> СПРАВОЧНИКИ </div>
            <ul class="items">
                <li> @Html.ActionLink("Сотрудники компании", "Index", "Employee", new { area = "Customer" }, null) </li>
                <li> @Html.ActionLink("МВЗ", "Index", "CostCenter", new { area = "Customer" }, null) </li>                
                <li> @Html.ActionLink("Контрагенты", "Index", "Contractor", new { area = "Customer" }, null) </li>                          
            </ul>
        </li>
        <li>
            <div class="sub-title"> ОТЧЕТЫ </div>
            <ul class="items">
                <li> @Html.ActionLink("Отчет по лицензиям", "UsedLicense", "Report", new { area = "Customer" }, null) </li>     
                <li> @Html.ActionLink("Список ПО по пользователям", "InstalledSoftware", "Report", new { area = "Customer" }, null) </li>  
                <li> @Html.ActionLink("Шахматка по услугам", "MaintenanceCross", "Report", new { area = "Customer" }, null) </li>                                   
            </ul>
        </li>
        <li style="border: none">   
            <div class="sub-title"> ОБМЕН </div>     
            <ul class="items">
                <li> @Html.ActionLink("МВЗ из Excel", "Index", "RawCostCenter", new { area = "Customer" }, null) </li>                  
                <li> @Html.ActionLink("Услуги SAP из Excel", "Index", "RawSAPMaintenance", new { area = "", layout = "Customer" }, null) </li>                                                                 
                <li> @Html.ActionLink("Услуги из AD", "Index", "RawADMaintenance", new { area = "", layout = "Customer" }, null) </li>
            </ul>        
        </li>
        @*<li style="border: none">               
            <ul class="items">
                <li>
                    <img src="~/Images/Logos/Rosneft.png" />
                </li>                       
            </ul>        
        </li>*@
    </ul>
}

@section Scripts { @RenderSection("scripts", required: false) }